version: "3.8"

services:
  frontend:
    build: .
    container_name: vite_dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL={VITE_BACKEND_URL}
      - VITE_ENCRYPTION_KEY=${VITE_ENCRYPTION_KEY}
    command: ["npm", "run", "dev", "--", "--host"]
